LOG_LEVEL = "DEBUG"

[Database]
host = ""
user = ""
password = ""
database = "markup-platform"

[TestDatabase]
host = ""
user = ""
password = ""
database = "markup-platform-test"

# Current database for migrations.
[Alembic]
database = "TestDatabase"

[Flask]
DEBUG = true
JWT_SECRET_KEY = ""
